In [116]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [117]:
df = pd.read_csv('detect_dataset.csv')
df.sample(5)

Output (S)          Ia          Ib          Ic        Va        Vb  \
2271           0   -3.616198   54.901474  -54.961250 -0.593020  0.408364   
3495           1  664.453661 -841.349439  -26.126327 -0.009282 -0.072336   
8545           1 -705.618688  147.908714  558.155915  0.044702  0.017537   
5740           0   49.894820  -34.822178  -12.714799  0.383544  0.214136   
360            0  -62.474545   40.728937   21.745607 -0.229660 -0.370757   

            Vc  Unnamed: 7  Unnamed: 8  
2271  0.184656         NaN         NaN  
3495  0.081618         NaN         NaN  
8545 -0.062239         NaN         NaN  
5740 -0.597680         NaN         NaN  
360   0.600417         NaN         NaN

In [118]:
df.drop('Unnamed: 7', axis=1, inplace=True)
df.drop('Unnamed: 8', axis=1, inplace=True)
df.sample(5)

Output (S)          Ia          Ib         Ic        Va        Vb  \
2797            1  542.798612  315.653074  52.330453  0.041631 -0.367089   
9940            0  -65.282528   90.458693 -28.644218 -0.406444 -0.182814   
536             1 -654.553627  -44.534723  12.950130  0.119844  0.168299   
9626            1  197.849241  -14.701682  17.580747  0.349715 -0.586068   
11292           0   12.344793  -30.001774  14.587543  0.589030 -0.222293   

             Vc  
2797   0.325458  
9940   0.589258  
536   -0.288143  
9626   0.236353  
11292 -0.366737

In [119]:
df.describe()

Output (S)            Ia            Ib            Ic            Va  \
count  12001.000000  12001.000000  12001.000000  12001.000000  12001.000000   
mean       0.457962      6.709369    -26.557793     22.353043      0.010517   
std        0.498250    377.158470    357.458613    302.052809      0.346221   
min        0.000000   -883.542316   -900.526951   -883.357762     -0.620748   
25%        0.000000    -64.348986    -51.421937    -54.562257     -0.237610   
50%        0.000000     -3.239788      4.711283     -0.399419      0.002465   
75%        1.000000     53.823453     69.637787     45.274542      0.285078   
max        1.000000    885.738571    889.868884    901.274261      0.609864   

                 Vb            Vc  
count  12001.000000  12001.000000  
mean      -0.015498      0.004980  
std        0.357644      0.349272  
min       -0.659921     -0.612709  
25%       -0.313721     -0.278951  
50%       -0.007192      0.008381  
75%        0.248681      0.289681  
max        0.627875      0.608243

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12001 entries, 0 to 12000
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Output (S)  12001 non-null  int64  
 1   Ia          12001 non-null  float64
 2   Ib          12001 non-null  float64
 3   Ic          12001 non-null  float64
 4   Va          12001 non-null  float64
 5   Vb          12001 non-null  float64
 6   Vc          12001 non-null  float64
dtypes: float64(6), int64(1)
memory usage: 656.4 KB


In [121]:
from sklearn.model_selection import train_test_split
x = df.drop('Output (S)', axis=1)
y = df['Output (S)']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [122]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(x_train)
x_train_scaled = pd.DataFrame(sc.transform(x_train))
x_test_scaled = pd.DataFrame(sc.transform(x_test))
x_train_scaled.sample(5)

0         1         2         3         4         5
3324 -2.318848  1.372117 -0.113561 -0.082327  0.853957 -0.793337
6744  0.338928  2.006641 -2.790205  0.089265  0.017195 -0.105855
5275 -2.059076  0.112476  2.431202 -0.129254  0.145910 -0.021685
9033 -0.004713 -0.040202  0.045722  1.670179 -1.130111 -0.493451
2305 -0.199653  0.262994 -0.067109 -0.723034 -0.952611  1.690522

In [123]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
import xgboost
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
# lr=LogisticRegression()
rf=RandomForestClassifier()
gb=GradientBoostingClassifier()
ada=AdaBoostClassifier()
xgb=xgboost.XGBClassifier()
knn=KNeighborsClassifier()
dt=DecisionTreeClassifier()
models={}
models['DecisionTreeClassifier']=dt
# models['LogisticRegression']=lr
models['RandomForestClassifier']=rf
models['GradientBoostingClassifier']=gb
models['AdaBoostClassifier']=ada
models['xgboost']=xgb
models['KNeighborsClassifier']=knn

def fit_and_score(models, x_train, x_test, y_train, y_test):
    np.random.seed(42)
    model_scores = {}
    for name, model in models.items():
        model.fit(x_train, y_train)
        pred = model.predict(x_test)
        print(name, accuracy_score(y_test, pred)*100)
        print('\n')
        print(confusion_matrix(y_test, pred))
        print('\n')
        print(classification_report(y_test, pred))
        print('\n')



In [124]:
fit_and_score(models, x_train_scaled, x_test_scaled, y_train, y_test)

DecisionTreeClassifier 99.54185755935026


[[1299    7]
 [   4 1091]]


              precision    recall  f1-score   support

           0       1.00      0.99      1.00      1306
           1       0.99      1.00      0.99      1095

    accuracy                           1.00      2401
   macro avg       1.00      1.00      1.00      2401
weighted avg       1.00      1.00      1.00      2401



RandomForestClassifier 99.7917534360683


[[1302    4]
 [   1 1094]]


              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1306
           1       1.00      1.00      1.00      1095

    accuracy                           1.00      2401
   macro avg       1.00      1.00      1.00      2401
weighted avg       1.00      1.00      1.00      2401



GradientBoostingClassifier 99.62515618492294


[[1303    3]
 [   6 1089]]


              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1306
           1  

In [125]:
y_test.shape

(2401,)

In [126]:
df = pd.read_csv('classData.csv')
df.sample(5)

G  C  B  A          Ia          Ib          Ic        Va        Vb  \
2818  0  1  1  0  -17.254729 -593.230691  612.860191 -0.433791 -0.024669   
7831  0  0  0  0  -71.063267   61.957937    6.229790 -0.141980 -0.429776   
3852  0  1  1  1  607.849635 -858.988902  253.210669 -0.013776 -0.027785   
3245  0  1  1  0  -41.716369 -333.765344  377.727669 -0.504371 -0.036645   
7085  0  0  0  0  -50.189269   12.259478   34.840525  0.345040 -0.583160   

            Vc  
2818  0.458460  
7831  0.571755  
3852  0.041560  
3245  0.541017  
7085  0.238120

In [127]:
x = df.drop(['G','C','B','A'],axis=1)
y = df[['G','C','B','A']]

y.sample(5)

G  C  B  A
522   1  0  0  1
6891  0  0  0  0
101   1  0  0  1
123   1  0  0  1
3119  0  1  1  0

In [128]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
sc.fit(x_train)
x_train_scaled = pd.DataFrame(sc.transform(x_train))
x_test_scaled = pd.DataFrame(sc.transform(x_test))
x_train_scaled.sample(5)

0         1         2         3         4         5
2984 -0.258092 -1.498423  2.088636 -0.115582  0.022584  0.085253
337   0.218434 -1.748363  1.789778 -0.098351 -0.011341  0.103635
1666 -0.151081 -0.069911  0.274401 -1.703285 -0.133236  1.730513
1050  1.344848 -1.821950  0.477954 -0.019036 -0.093124  0.112574
2903 -0.015487 -1.670969  1.995798 -0.103105  0.003660  0.092824

In [129]:
model = RandomForestClassifier(max_depth=10, min_samples_leaf=1, min_samples_split=2, n_estimators=200)
model.fit(x_train_scaled, y_train)
y_pred = pd.DataFrame(model.predict(x_test_scaled))
y_pred.columns = ['G','C','B','A']
print(accuracy_score(y_test, y_pred))

0.8328035600762873


In [130]:
y_pred.sample(5)

G  C  B  A
1130  0  1  1  1
176   1  0  1  1
1129  1  0  0  1
843   0  1  1  1
1177  1  0  1  1

In [131]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.81      0.82       691
           1       1.00      0.99      1.00       611
           2       1.00      0.99      0.99       849
           3       1.00      1.00      1.00       890

   micro avg       0.96      0.95      0.96      3041
   macro avg       0.96      0.95      0.95      3041
weighted avg       0.96      0.95      0.96      3041
 samples avg       0.67      0.67      0.67      3041



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [144]:
model = DecisionTreeClassifier()
model.fit(x_train_scaled, y_train)
pred = model.predict(x_test_scaled)
pred = pd.DataFrame(pred)
pred.columns = ['G','C','B','A']
print(classification_report(y_test, pred))


              precision    recall  f1-score   support

           0       0.90      0.87      0.89       691
           1       1.00      1.00      1.00       611
           2       1.00      1.00      1.00       849
           3       1.00      1.00      1.00       890

   micro avg       0.98      0.97      0.97      3041
   macro avg       0.98      0.97      0.97      3041
weighted avg       0.98      0.97      0.97      3041
 samples avg       0.68      0.68      0.68      3041



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [138]:
model = xgboost.XGBClassifier()
model.fit(x_train_scaled, y_train)
pred = model.predict(x_test_scaled)
pred = pd.DataFrame(pred)
pred.columns = ['G','C','B','A']
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.81      0.79      0.80       691
           1       1.00      1.00      1.00       611
           2       1.00      1.00      1.00       849
           3       1.00      1.00      1.00       890

   micro avg       0.96      0.95      0.95      3041
   macro avg       0.95      0.95      0.95      3041
weighted avg       0.96      0.95      0.95      3041
 samples avg       0.67      0.67      0.67      3041



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [139]:
model = KNeighborsClassifier()
model.fit(x_train_scaled, y_train)
pred = model.predict(x_test_scaled)
pred = pd.DataFrame(pred)
pred.columns = ['G','C','B','A']
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.79      0.78      0.78       691
           1       1.00      1.00      1.00       611
           2       1.00      0.99      1.00       849
           3       1.00      1.00      1.00       890

   micro avg       0.95      0.95      0.95      3041
   macro avg       0.95      0.94      0.94      3041
weighted avg       0.95      0.95      0.95      3041
 samples avg       0.67      0.67      0.66      3041



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
